ribbon:
    eureka:
        enabled: false
server:
    port: 8441
    ssl:
      key-store-type: PKCS12
      key-store: classpath:tyb433keystore.p12
      key-store-password: 12345678
      key-alias: tomcat
management:
    security:
        enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
        require-ssl: true
zuul:
    routes:
        movie-service2:
            url: http://localhost:8090
#eureka:         #tells about the Eureka server details and its refresh time
#    instance:
#        leaseRenewalIntervalInSeconds: 1
#        leaseExpirationDurationInSeconds: 2
#    client:
#        serviceUrl:
#            defaultZone: http://127.0.0.1:8091/eureka/
#        healthcheck:
#            enabled: true
#        lease:
#            duration: 5

logging:
    level:
        com.example.howtodoinjava: DEBUG
spring:
    application:
        name: zuul-gateway